{% set name = "jupyter-ui-poll" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c194c7222ab18646f9069ecdcd11579e4a62ec269fd4535b5702693f805e374

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - ipython
  run:
    - python >=3.6
    - ipython

test:
  imports:
    - jupyter_ui_poll
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/kirill888/jupyter-ui-poll
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Block jupyter cell execution while interacting with widgets
  description: |
    Block Jupyter cell execution while interacting with widgets.

    This library is for people familiar with `ipywidgets` who want to solve the
    following problem:

    1. Display User Interface in Jupyter using `ipywidgets`  or similar
    2. Wait for data to be entered (this step is surprisingly non-trivial to implement)
    3. Use entered data in cells below

  doc_url: https://jupyter-ui-poll.readthedocs.io/en/latest/
  dev_url: https://github.com/kirill888/jupyter-ui-poll

extra:
  recipe-maintainers:
    - kirill888
