{% set name = "jupyter-ui-poll" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 439fa936a37e09c0d3eaa9b835eeb0da2edaec3db06eade43a01d614a528424c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - ipython
  run:
    - python >={{ python_min }}
    - ipython

test:
  imports:
    - jupyter_ui_poll
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/kirill888/jupyter-ui-poll
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Block jupyter cell execution while interacting with widgets
  description: |
    Block Jupyter cell execution while interacting with widgets.

    This library is for people familiar with `ipywidgets` who want to solve the
    following problem:

    1. Display User Interface in Jupyter using `ipywidgets`  or similar
    2. Wait for data to be entered (this step is surprisingly non-trivial to implement)
    3. Use entered data in cells below

  doc_url: https://jupyter-ui-poll.readthedocs.io/en/latest/
  dev_url: https://github.com/kirill888/jupyter-ui-poll

extra:
  recipe-maintainers:
    - kirill888
